theme: jekyll-theme-cayman
name: helm-trivy-vulnerability-exporter
description: Trivy Vulnerability Exporter Helm Repository
github:
  repository_url: https://github.com/lucasafonsokremer/trivy-vulnerability-exporter
buttons:
  zip_url: https://github.com/lucasafonsokremer/trivy-vulnerability-exporter
  zip_title: View Documentation
  zip_hide: false
  tar_hide: true
  github_hide: true
