theme: jekyll-theme-cayman
name: helm-trivy-vulnerability-exporter
description: Trivy Vulnerability Exporter Helm Repository
github:
  url: https://github.com/lucasafonsokremer/trivy-vulnerability-exporter
