theme: jekyll-theme-cayman
name: helm-trivy-vulnerability-exporter
description: Teste 2 Trivy Vulnerability Exporter Helm Repository
github:
  another_url: https://github.com/lucasafonsokremer/trivy-vulnerability-exporter
