theme: jekyll-theme-cayman
name: helm-trivy-vulnerability-exporter
description: Trivy Vulnerability Exporter Helm Repository
github:
  repository_url: https://github.com/lucasafonsokremer/trivy-vulnerability-exporter
  repositoty_name: trivy-vulnerability-exporter
