{{- if .Values.clusterRoleBinding.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "trivyvulnerabilityexporter.name" . }}
  labels:
    {{- include "trivyvulnerabilityexporter.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "trivyvulnerabilityexporter.serviceAccountName" . }}
  namespace: {{ .Values.namespaceName }}
roleRef:
  kind: ClusterRole
  name: {{ include "trivyvulnerabilityexporter.name" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
