{{- if .Values.clusterRole.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "trivyVulnerabilityExporter.name" . }}
  labels:
    {{- include "trivyVulnerabilityExporter.labels" . | nindent 4 }}
  {{ if .Values.clusterRole.annotations }}
  annotations:
    {{ with .Values.clusterRole.annotations }}
    {{ toYaml . | nindent 4 }}
    {{ end }}
  {{ end }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets", "daemonsets"]
  verbs: ["list"]
- apiGroups: ["batch"]
  resources: ["cronjobs"]
  verbs: ["list"]
{{- end }}
