{{- if .Values.namespace.create -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  labels:
    {{- include "trivyVulnerabilityExporter.labels" . | nindent 4 }}
  {{ if .Values.namespace.annotations }}
  annotations:
    {{ with .Values.namespace.annotations }}
    {{ toYaml . | nindent 4 }}
    {{ end }}
  {{ end }}
{{- end }}
