{{- if .Values.namespace.create -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaceName }}
  labels:
    {{- include "trivyvulnerabilityexporter.labels" . | nindent 4 }}
{{- end }}
