{{- if .Values.role.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "trivyvulnerabilityexporter.name" . }}
  namespace: {{ .Values.namespaceName }}
  labels:
    {{- include "trivyvulnerabilityexporter.labels" . | nindent 4 }}
  {{ if .Values.role.annotations }}
  annotations:
    helm.sh/release-name: {{ include "trivyvulnerabilityexporter.name" . }}
    helm.sh/release-namespace: {{ .Values.namespaceName }}
    {{ with .Values.role.annotations }}
    {{ toYaml . | nindent 4 }}
    {{ end }}
  {{ end }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "delete"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
{{- end }}
