{{- if .Values.service.create -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "trivyvulnerabilityexporter.name" . }}
  namespace: {{ .Values.namespaceName }}
  labels:
    {{- include "trivyvulnerabilityexporter.labels" . | nindent 4 }}
  {{ if .Values.service.annotations }}
  annotations:
    {{ with .Values.service.annotations }}
    {{ toYaml . | nindent 4 }}
    {{ end }}
  {{ end }}
spec:
  clusterIP: None
  ports:
    - port: 9321
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "trivyvulnerabilityexporter.selectorLabels" . | nindent 4 }}
{{- end }}
